baseURL: https://cttnguyen.github.io/7c60903edaf0efcc501c0f689c01bef2773947cc
title: "#TheLuckettest"
theme: meghna-hugo
paginate: '6'
summaryLength: '15'
disqusShortname: ''
disableLanguages: 
params:
  author: Themefisher
  cookies:
    enable: no
    expire_days: 2
  description: Responsive Multipurpose Parallax Hugo Template
  google_analytics_id: ''
  map:
    enable: yes
  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/themify-icons/themify-icons.css
      - link: plugins/magnific-popup/magnific-popup.css
      - link: plugins/slick/slick.css
      - link: fonts/myfonts.css
      - link: https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap
    js:
      - link: plugins/jquery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/slick/slick.min.js
      - link: plugins/shuffle/shuffle.min.js
      - link: plugins/magnific-popup/jquery.magnific-popup.min.js
      - link: plugins/lazy-load/lozad.min.js
      - link: plugins/google-map/map.js
  post_share: yes
  preloader:
    enable: no
  social:
    - icon: ti-facebook
      link: '#'
    - icon: ti-twitter-alt
      link: '#'
    - icon: ti-youtube
      link: '#'
    - icon: ti-linkedin
      link: '#'
    - icon: ti-dribbble
      link: '#'
    - icon: ti-pinterest
      link: '#'
Languages:
  en:
    contentDir: content/english
    copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com)
      & Developed by [Gethugothemes](https://gethugothemes.com)
    home: Home
    languageCode: en-us
    languageName: En
    menu:
      main:
        - name: About
          pre: '#'
          url: about
          weight: 1
        - name: Details
          pre: '#'
          url: details
          weight: 2
        - name: RSVP
          pre: '#'
          url: rsvp
          weight: 3
        - name: Registry
          pre: '#'
          url: registry
          weight: 4
        - name: Gallery
          pre: '#'
          url: gallery
          weight: 5
        - name: Blog
          pre: '#'
          url: blog
          weight: 6
        - name: FAQ
          pre: '#'
          url: FAQ
          weight: 7
    weight: 1

