---
title: "Crystal and Daniel's Wedding"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---

<style>                     
.navbar, [data-toggle=tab], .navbar-brand{ 
  background-color:#003366!important; 
  border-color:#003366; 
  color:white!important; 
}
.bgred {
  background-color:#003366;
  color:white;
}
</style>       

```{r setup, include=FALSE}
library(flexdashboard)
```

Home 
=======================================================================

Row 
-----------------------------------------------------------------------
### 

#### Crystal and Daniel are Getting Married!

```{r, echo=FALSE}
htmltools::tags$iframe(
    src="timecounter.html",
    width="350", 
    height="150",
    scrolling="no", 
    seamless="seamless", 
    frameBorder="0"
  )
```

Events
=======================================================================

Travel
=======================================================================

Registry
=======================================================================

RSVP
=======================================================================

Gallery
=======================================================================

FAQs
=======================================================================

DIY Wedding Blog
=======================================================================


