---
title: "Travel"
author: "Crystal Nguyen"
date: "November 2, 2019"
output: html_document
---


<div class = "row">
<div class = "col-md-6">

###### Vietnamese Tea Ceremony

**Friday, February 26th, 2021**

Northwest Houston Vietnamese Alliance Church

5133 Addicks Satsuma Rd, Cypress, TX 77084

Ceremony (Time TBA) 
<!-- 5:00 pm -->

Dinner to Follow
 
</div>
<div class = "col-md-6">

###### Wedding and Reception

**Saturday, February 27th, 2021**

The SPRINGS in Cypress

12612 Malcomson Rd, Cypress, TX 77070

Ceremony (Time TBA)
<!-- 4:00 pm -->

Dinner and Drinks to Follow

</div>
</div>

<br>
<br>

###### Lodging

**Element Houston Vintage Park** ([Book Now](https://www.marriott.com/event-reservations/reservation-link.mi?id=1583424691554&key=GRP&app=resvlink))

A block of rooms has been reserved for $96/night. All rooms include a kitchennette, and all reservations include free WiFi, parking, and breakfast. Please use the link above or mention "Nguyen-Luckett Wedding" on the phone to reserve your stay at group rates!

<br>
<br>

###### Getting Here

<div class = "row">
<div class = "col-md-6">
**George Bush Intercontinental Airport**
<br>
35 minutes to Cypress
<br>
Recommended for most airlines

</div>
<div class = "col-md-6">
**William P. Hobby Airport**
<br>
45 minutes to Cypress
<br>
Recommended for Southwest airlines
</div>
</div>


```{r, echo = FALSE}
htmltools::tags$iframe(
    src="WeddingMap.html",
    width="660",
    height="500",
    seamless="seamless",
    frameBorder="0"
  )
```

<br>
<br>

###### Getting Around

More information coming soon!

<br>
<br>

###### Things To Do
<div align="left">
**Vintage Park Shopping Mall**
<div class="nobullet">
* 110 Vintage Park Blvd., Houston TX, 77070
* Across the street from Element Houston Vintage Park Hotel
* Features shops, spas, dining, and bars ([Visit](http://www.vintageparkhouston.com/){target="_blank"})
</div>
**The Houston Zoo**
<div class="nobullet">
* 6200 Hermann Park Dr., Houston, TX 77030
* The 2nd most visited zoo in the US and home to over 6,000 animals ([Visit](https://www.houstonzoo.org){target="_blank"})
</div>
**Space Center Houston**
<div class="nobullet">
* 1601 NASA Pkwy., Houston, TX 77058
* Two words: outer space ([Visit](https://spacecenter.org/){target="_blank"})
</div>
**Houston Museum District**
<div class="nobullet">
* Includes 19 museums in 4 zones ([Visit](https://houmuse.org/){target="_blank"})
* Crystal's favorite: The museum of natural science
</div>
</div>


